ALTER TABLE notes ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT NOW();
ALTER TABLE notes ADD COLUMN modified_at TIMESTAMP NOT NULL DEFAULT NOW();
ALTER TABLE notes ADD COLUMN is_template BOOLEAN DEFAULT FALSE;
ALTER TABLE notes ADD COLUMN access VARCHAR(255) NOT NULL;
ALTER TABLE notes ADD COLUMN owner_id BIGINT;